title: Fanning
description: Embedded Linux Blog

theme: jekyll-rtd-theme

# debug:
#   compress: true
#   dist: false
#   shortcodes: true

readme_index:
  with_frontmatter: true

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-github-metadata

repository: username/project

exclude:
  - Makefile
  - CNAME
  - LICENSE
  - update.sh
  - Gemfile
  - Gemfile.lock
  - requirements.txt
  - node_modules
  - package.json
  - package-lock.json
  - webpack.config.js
  - jekyll-rtd-theme.gemspec
# Google Ads
adsense:
  client_id: 'ca-pub-2950224298461248' # Google Adsense client ID
  
